feat: html and css code of the block benefits
IVKrylova/routes-of-my-city pull request #2
Opened 2023-03-17 05:28 UTC by IVKrylova

Блок Benefits

2023-03-17 09:42 UTC, MarinaKrasnov requested changes
feat/header выдал ошибку линта, это  к сожалению выдает ошибку.

2023-03-17 09:52 UTC, IVKrylova commented
> feat/header выдал ошибку линта, это к сожалению выдает ошибку.

а что за ошибка?

2023-03-17 09:57 UTC, MarinaKrasnov commented
> > feat/header выдал ошибку линта, это к сожалению выдает ошибку.
> 
> а что за ошибка?
WARNING in [eslint]
src\components\App\App.js
  Line 11:19:  'setIsLogin' is assigned a value but never used  no-unused-vars

и по этой ветке БЕЛЫЙ ЭКРАН

2023-03-17 09:59 UTC, IVKrylova commented
> > > feat/header выдал ошибку линта, это к сожалению выдает ошибку.
> > 
> > 
> > а что за ошибка?
> > WARNING in [eslint]
> > src\components\App\App.js
> > Line 11:19:  'setIsLogin' is assigned a value but never used  no-unused-vars
> 
> и по этой ветке БЕЛЫЙ ЭКРАН

Это норм, setIsLogin будет дальше использоваться при авторизации - ошибка пропадет

2023-03-17 09:59 UTC, IVKrylova commented
> > > feat/header выдал ошибку линта, это к сожалению выдает ошибку.
> > 
> > 
> > а что за ошибка?
> > WARNING in [eslint]
> > src\components\App\App.js
> > Line 11:19:  'setIsLogin' is assigned a value but never used  no-unused-vars
> 
> и по этой ветке БЕЛЫЙ ЭКРАН

сейчас запущу у себя, посмотрю, почему белый экран

2023-03-17 10:05 UTC, IVKrylova commented
> > > feat/header выдал ошибку линта, это к сожалению выдает ошибку.
> > 
> > 
> > а что за ошибка?
> > WARNING in [eslint]
> > src\components\App\App.js
> > Line 11:19:  'setIsLogin' is assigned a value but never used  no-unused-vars
> 
> и по этой ветке БЕЛЫЙ ЭКРАН

Локально все работает http://joxi.net/krDyq6WUdW47bm

в консоли есть какие-нибудь ошибки?

2023-03-17 10:44 UTC, MarinaKrasnov requested changes
ок, у меня не подтягивалась ветка. сейчас подтянулась. я вижу кривой текст на 294 пикселя,

2023-03-19 09:29 UTC, MarinaKrasnov approved these changes

2023-03-19 09:33 UTC, merged